[build]
  publish = "dist/"
  command = "npm run build"

[[redirects]]
  from = "/"
  to = "/uk"
  status = 301
  force = true
  conditions = {Language = ["uk"]}

[[redirects]]
  from = "/"
  to = "/ru"
  status = 301
  force = true
  conditions = {Language = ["ru"]}

[[redirects]]
  from = "/"
  to = "/en"
  status = 301
  force = true
  conditions = {Language = ["en"]}

[[redirects]]
  from = "/"
  to = "/uk"
  status = 302

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/assets"
    [headers.values]
    Access-Control-Allow-Origin = "*"